// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nixxxon/entdemo/ent/predicate"
	"github.com/nixxxon/entdemo/ent/todohack"
)

// TodoHackDelete is the builder for deleting a TodoHack entity.
type TodoHackDelete struct {
	config
	hooks    []Hook
	mutation *TodoHackMutation
}

// Where appends a list predicates to the TodoHackDelete builder.
func (thd *TodoHackDelete) Where(ps ...predicate.TodoHack) *TodoHackDelete {
	thd.mutation.Where(ps...)
	return thd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (thd *TodoHackDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, thd.sqlExec, thd.mutation, thd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (thd *TodoHackDelete) ExecX(ctx context.Context) int {
	n, err := thd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (thd *TodoHackDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(todohack.Table, sqlgraph.NewFieldSpec(todohack.FieldID, field.TypeUUID))
	if ps := thd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, thd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	thd.mutation.done = true
	return affected, err
}

// TodoHackDeleteOne is the builder for deleting a single TodoHack entity.
type TodoHackDeleteOne struct {
	thd *TodoHackDelete
}

// Where appends a list predicates to the TodoHackDelete builder.
func (thdo *TodoHackDeleteOne) Where(ps ...predicate.TodoHack) *TodoHackDeleteOne {
	thdo.thd.mutation.Where(ps...)
	return thdo
}

// Exec executes the deletion query.
func (thdo *TodoHackDeleteOne) Exec(ctx context.Context) error {
	n, err := thdo.thd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{todohack.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (thdo *TodoHackDeleteOne) ExecX(ctx context.Context) {
	if err := thdo.Exec(ctx); err != nil {
		panic(err)
	}
}
