// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nixxxon/entdemo/ent/predicate"
	"github.com/nixxxon/entdemo/ent/todohack"
)

// TodoHackUpdate is the builder for updating TodoHack entities.
type TodoHackUpdate struct {
	config
	hooks    []Hook
	mutation *TodoHackMutation
}

// Where appends a list predicates to the TodoHackUpdate builder.
func (thu *TodoHackUpdate) Where(ps ...predicate.TodoHack) *TodoHackUpdate {
	thu.mutation.Where(ps...)
	return thu
}

// SetOtherID sets the "other_id" field.
func (thu *TodoHackUpdate) SetOtherID(u uuid.UUID) *TodoHackUpdate {
	thu.mutation.SetOtherID(u)
	return thu
}

// SetNillableOtherID sets the "other_id" field if the given value is not nil.
func (thu *TodoHackUpdate) SetNillableOtherID(u *uuid.UUID) *TodoHackUpdate {
	if u != nil {
		thu.SetOtherID(*u)
	}
	return thu
}

// ClearOtherID clears the value of the "other_id" field.
func (thu *TodoHackUpdate) ClearOtherID() *TodoHackUpdate {
	thu.mutation.ClearOtherID()
	return thu
}

// SetName sets the "name" field.
func (thu *TodoHackUpdate) SetName(s string) *TodoHackUpdate {
	thu.mutation.SetName(s)
	return thu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (thu *TodoHackUpdate) SetNillableName(s *string) *TodoHackUpdate {
	if s != nil {
		thu.SetName(*s)
	}
	return thu
}

// Mutation returns the TodoHackMutation object of the builder.
func (thu *TodoHackUpdate) Mutation() *TodoHackMutation {
	return thu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (thu *TodoHackUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, thu.sqlSave, thu.mutation, thu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (thu *TodoHackUpdate) SaveX(ctx context.Context) int {
	affected, err := thu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (thu *TodoHackUpdate) Exec(ctx context.Context) error {
	_, err := thu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thu *TodoHackUpdate) ExecX(ctx context.Context) {
	if err := thu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (thu *TodoHackUpdate) check() error {
	if v, ok := thu.mutation.Name(); ok {
		if err := todohack.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TodoHack.name": %w`, err)}
		}
	}
	return nil
}

func (thu *TodoHackUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := thu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(todohack.Table, todohack.Columns, sqlgraph.NewFieldSpec(todohack.FieldID, field.TypeUUID))
	if ps := thu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if thu.mutation.RefCleared() {
		_spec.ClearField(todohack.FieldRef, field.TypeUUID)
	}
	if value, ok := thu.mutation.OtherID(); ok {
		_spec.SetField(todohack.FieldOtherID, field.TypeUUID, value)
	}
	if thu.mutation.OtherIDCleared() {
		_spec.ClearField(todohack.FieldOtherID, field.TypeUUID)
	}
	if value, ok := thu.mutation.Name(); ok {
		_spec.SetField(todohack.FieldName, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, thu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todohack.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	thu.mutation.done = true
	return n, nil
}

// TodoHackUpdateOne is the builder for updating a single TodoHack entity.
type TodoHackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TodoHackMutation
}

// SetOtherID sets the "other_id" field.
func (thuo *TodoHackUpdateOne) SetOtherID(u uuid.UUID) *TodoHackUpdateOne {
	thuo.mutation.SetOtherID(u)
	return thuo
}

// SetNillableOtherID sets the "other_id" field if the given value is not nil.
func (thuo *TodoHackUpdateOne) SetNillableOtherID(u *uuid.UUID) *TodoHackUpdateOne {
	if u != nil {
		thuo.SetOtherID(*u)
	}
	return thuo
}

// ClearOtherID clears the value of the "other_id" field.
func (thuo *TodoHackUpdateOne) ClearOtherID() *TodoHackUpdateOne {
	thuo.mutation.ClearOtherID()
	return thuo
}

// SetName sets the "name" field.
func (thuo *TodoHackUpdateOne) SetName(s string) *TodoHackUpdateOne {
	thuo.mutation.SetName(s)
	return thuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (thuo *TodoHackUpdateOne) SetNillableName(s *string) *TodoHackUpdateOne {
	if s != nil {
		thuo.SetName(*s)
	}
	return thuo
}

// Mutation returns the TodoHackMutation object of the builder.
func (thuo *TodoHackUpdateOne) Mutation() *TodoHackMutation {
	return thuo.mutation
}

// Where appends a list predicates to the TodoHackUpdate builder.
func (thuo *TodoHackUpdateOne) Where(ps ...predicate.TodoHack) *TodoHackUpdateOne {
	thuo.mutation.Where(ps...)
	return thuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (thuo *TodoHackUpdateOne) Select(field string, fields ...string) *TodoHackUpdateOne {
	thuo.fields = append([]string{field}, fields...)
	return thuo
}

// Save executes the query and returns the updated TodoHack entity.
func (thuo *TodoHackUpdateOne) Save(ctx context.Context) (*TodoHack, error) {
	return withHooks(ctx, thuo.sqlSave, thuo.mutation, thuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (thuo *TodoHackUpdateOne) SaveX(ctx context.Context) *TodoHack {
	node, err := thuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (thuo *TodoHackUpdateOne) Exec(ctx context.Context) error {
	_, err := thuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thuo *TodoHackUpdateOne) ExecX(ctx context.Context) {
	if err := thuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (thuo *TodoHackUpdateOne) check() error {
	if v, ok := thuo.mutation.Name(); ok {
		if err := todohack.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TodoHack.name": %w`, err)}
		}
	}
	return nil
}

func (thuo *TodoHackUpdateOne) sqlSave(ctx context.Context) (_node *TodoHack, err error) {
	if err := thuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todohack.Table, todohack.Columns, sqlgraph.NewFieldSpec(todohack.FieldID, field.TypeUUID))
	id, ok := thuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TodoHack.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := thuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todohack.FieldID)
		for _, f := range fields {
			if !todohack.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != todohack.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := thuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if thuo.mutation.RefCleared() {
		_spec.ClearField(todohack.FieldRef, field.TypeUUID)
	}
	if value, ok := thuo.mutation.OtherID(); ok {
		_spec.SetField(todohack.FieldOtherID, field.TypeUUID, value)
	}
	if thuo.mutation.OtherIDCleared() {
		_spec.ClearField(todohack.FieldOtherID, field.TypeUUID)
	}
	if value, ok := thuo.mutation.Name(); ok {
		_spec.SetField(todohack.FieldName, field.TypeString, value)
	}
	_node = &TodoHack{config: thuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, thuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todohack.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	thuo.mutation.done = true
	return _node, nil
}
