// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)

// TodoHack is the predicate function for todohack builders.
type TodoHack func(*sql.Selector)
